apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: liiamj234/cicd-k8s:6b7ae4b
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "latest"